Find the Difference

You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"

Example 2:

Input: s = "", t = "y"
Output: "y"

Solution:


 class Solution {
    public char findTheDifference(String s, String t) {
        char c=0;
        for(char ch:s.toCharArray()) c^=ch;
        for(char ch:t.toCharArray()) c^=ch;
        return c;
    }
}
